version: "3.3"
services:



  db:
    image: postgres:12.6
    container_name: db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/1-create.sql
    networks:
      - app



  webservice:
    container_name: webservice
    build: .\multicertDevChallenge
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    networks:
      - app
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      
      
  angular-frontend:
    container_name: frontend-portal
    build: .\client
    ports:
      - '9000:80'
    environment:
      - NODE_ENV=production

networks:
  app: {}